### ISSUE TITLE
Feature: Company scraping

### ISSUE THREAD

**Issue by dtquandt** [hakimkhalafi/linkedin-scraper#1]
Hi, I found this repo through your reddit post.

Would this script be easily applicable to scraping company information from a list of company URLs? Just figured I'd get your thoughts on this before dipping my toes in since I'm only a beginner.

Cheers.

**Comment by hakimkhalafi** [comment]
Hi, not sure, it entirely depends on how they have structured their company pages :)

If you do find out a nice way to also scrape company pages, feel free to make a pull request

Best of luck!
